### ISSUE TITLE
import rospy error

### ISSUE THREAD

**Issue by harinchandu** [mrl-athomelab/ros-face-recognition#1]
hi, 
unable to import rospy
ImportError: No module named 'rospy'

please help,
thanks and regards.

**Comment by ahmdrz** [comment]
Hi
Did you install ROS ?

What is your operation system ?

**Comment by harinchandu** [comment]
hi,
its ubuntu 16.04

**Comment by harinchandu** [comment]
i am using python3 to run this python program

**Comment by ahmdrz** [comment]
This repository is based on ROS.
To see how you can use in python :
1. [dlib website](http://dlib.org)
2. [ageitgey's repository](https://github.com/ageitgey/face_recognition)
